### ISSUE TITLE
Double quotes cause issues

### ISSUE THREAD

**Issue by RasmusBertell** [paytrail/e2-module#16]
**Describe the bug**

Since double quotes are not properly escaped they cause a mismatch in AUTHCODE.

**Steps to Reproduce**

1. Order a product with a double quote in it's name
2. You are redirected to page with AUTHCODE mismatch error

**Expected behaviour**

Value should be escaped and AUTHCODES should match.

**Actual behaviour**

If a product, for example, has a double quote in it's name it will cause a mismatch in AUTHCODE, since the double quote is considered when calculating the initial AUTHCODE, but when the value is placed in template it is not properly escaped and causes breakage.

**Additional context**

I made a quick fix for this by adding `htmlspecialchars($value, ENT_COMPAT)` to `src/Templates/PaymentForm.phtml`, but it might be preferable to do it sooner, I don't have proper knowledge of this codebase to be sure.

**Comment by Jipsukka** [comment]
@RasmusBertell Issue is now fixed in version 1.1.1
