### ISSUE TITLE
Not compliant with psr-4 autoloading standard

### ISSUE THREAD

**Issue by aruohtula** [paytrail/e2-module#8]
The e2-module does not comply with the psr-4 autoloading standard. When running `composer update --optimize-autoloader` you see Deprecation Notices for all of the E2Module classes, like this:

`Deprecation Notice: Class Paytrail\E2Module\Merchant located in ./vendor/paytrail/e2-module/src/app/Merchant.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0.`

My Symfony app could not autoload the classes after installing with `composer require paytrail/e2-module` or after a `composer update`, thowing ClassNotFoundExceptions. Renaming the src/app folder to src/E2Module seems to fix the problem.

**Comment by nikoheikkila** [comment]
Thanks for raising the issue, @aruohtula. We haven't tried importing this library to a Symfony app but it's probably common in all frameworks. We will investigate and fix this. 👍

**Comment by nikoheikkila** [comment]
@aruohtula There's now a new version if you can try running `composer update` on your project.

**Comment by aruohtula** [comment]
Thank you @nikoheikkila, it works now!
